import '../../home-alpha.css';
import type { Metadata } from 'next';
import { HomeDashboard,type HomeInitialData } from '@/components/reference-home';
import type { PublicationCardData } from '@/lib/types';
export const metadata:Metadata={title:'Предпросмотр утверждённого дизайна',robots:{index:false,follow:false}};
// Reference content is isolated here. Production homepage always uses the real API.
const names=['Artemis','pixelvoid','neonride','sysadmin','mindwave','hollow','kibershot','deeplight','Linuxoid','vantuzz'];
const labels=['Новости','Технологии','Программирование','Дизайн и медиа','Игры','Железо','Софт','Интернет и сети','Общение','Торговая площадка','Архив'];
const slugs=['news','technology','code','design','games','hardware','software','network','chat','market','archive'];
const colors=['#879bae','#679bd0','#7696af','#bc6097','#8768b7','#b28558','#79927e','#4d9f87','#779294','#b58d75','#8e959c'];
const communities=labels.map((name,i)=>({id:`reference-${i}`,slug:slugs[i],name,description:name,subscriberCount:0,onlineCount:0,publicationCount:[12,248,186,73,211,97,134,89,321,54,16][i],accentColor:colors[i],parent:null}));
const titles=['Какой дистрибутив Linux выбрать в 2026?','Сборка ПК до 100.000₽ — советы','Альтернативы Photoshop в 2026','Лучшие игры осени 2026','Настройка домашнего сервера','Куда движется ИИ в 2026?'];
const descriptions=['Планирую перейти на Linux, интересует ваш опыт и рекомендации. Нужен стабильный дистрибутив для работы и игр. Какие варианты…','Нужна помощь со сборкой. Основная задача — игры в 2K, иногда работа с монтажом. Какую конфигурацию порекомендуете?','Хочется достойные аналоги для работы с графикой. Интересуют как платные, так и бесплатные решения. Делитесь опытом!','Делимся впечатлениями от главных релизов этого сезона. Во что играете сейчас? Какие игры действительно стоят внимания?','Хочу поднять свой сервер для бэкапов и медиа. Посоветуйте конфигурацию, софт и расскажите о подводных камнях.','Обсуждаем последние достижения и реальные кейсы применения. Как ИИ влияет на наши профессии и повседневную жизнь?'];
const feed:PublicationCardData[]=titles.map((title,i)=>({id:`reference-topic-${i}`,slug:`reference-topic-${i}`,format:'TOPIC',type:'DISCUSSION',title,excerpt:descriptions[i],createdAt:'2026-09-30T08:27:00Z',author:{username:names[(i+5)%10],displayName:names[(i+5)%10]},community:communities[[1,5,3,4,7,1][i]],commentCount:[42,67,28,91,15,76][i],reactionCount:0,viewCount:[3100,4800,2100,6400,1200,5900][i],tags:[],lastComment:{id:`reference-reply-${i}`,excerpt:'Обсуждение',createdAt:'2026-09-30T08:27:00Z',author:{username:names[[5,0,1,2,3,4][i]],displayName:names[[5,0,1,2,3,4][i]]}}}));
const announcements:PublicationCardData[]=[{...feed[0],id:'reference-news-1',title:'Обновление правил форума',excerpt:'Мы переработали правила с учётом пожеланий сообщества. Ознакомьтесь с ключевыми изменениями, чтобы сделать форум лучше для всех.',createdAt:'2026-09-25T12:00:00Z',isOfficial:true,commentCount:8,viewCount:12400},{...feed[1],id:'reference-news-2',title:'Запуск сезонного ивента «Осень 2026»',excerpt:'Новые активности, награды, специальные роли и конкурсные задания. Присоединяйтесь — будет интересно!',createdAt:'2026-09-22T12:00:00Z',isOfficial:false,commentCount:48,viewCount:8700}];
const data:HomeInitialData={communities,feed,announcements,events:[],overview:{stats:{users:52431,communities:11,topics:126982,messages:1842771,usersOnline:0,recordOnline:0,newestUser:{username:'shadow.mp4',displayName:'shadow.mp4'}},weekly:{likes:[],activity:names.map((displayName,i)=>({username:displayName,displayName,score:2948-i*213,reactionCount:0,topicCount:0,commentCount:[2948,2337,1982,1625,1481,1372,1291,1047,934,812][i]}))},discussed:feed.map(item=>({...item,viewCount:item.viewCount??0})),pulse:{recentReplies:[],activeTopics:[0,3,1,5,4].map(i=>({slug:feed[i].slug,title:feed[i].title,replyCount:feed[i].commentCount}))}}};
export default function PreviewHome(){return <HomeDashboard initialData={data} demo/>;}
