import type { Metadata } from 'next';
import { HomeDashboard, type HomeInitialData } from '@/components/reference-home';
import type { PublicationCardData } from '@/lib/types';

export const metadata: Metadata = { title: 'FORRUM — демонстрация дизайна', robots: { index: false, follow: false } };
const names = ['Нора Веб', 'Pixel Lab', 'Макс Стрим', 'Анна AI', 'Денис Код', 'Юлия Арт'];
const categories = ['Нейросети и модели', 'Кодинг с AI', 'Изображения и видео', 'Работа и заработок', 'Промпты и агенты', 'Свободное общение'];
const colors = ['#759848', '#5c92bc', '#a978ba', '#b8974b', '#529b88', '#8d949c'];
const communities = categories.map((name, i) => ({ id: `demo-${i}`, slug: `demo-${i}`, name, description: name, subscriberCount: [12400,8300,6700,5100,4800,3200][i], onlineCount: [342,125,84,61,96,47][i], publicationCount: 120 + i * 32, accentColor: colors[i], parent: null }));
const titles = ['Какая нейросеть стала вашим рабочим инструментом?', 'Покажите проект, который вы собрали с AI', 'Как сохранить одного персонажа в серии изображений?', 'Где AI действительно экономит время в работе?', 'Делимся промптами: что сработало на практике', 'Что вы создали на этой неделе?'];
const excerpts = ['Сравниваем реальные задачи, удобство и результат. Поделитесь своим опытом.', 'Небольшой бот, сайт или приложение — расскажите, что получилось и где нужна помощь.', 'Собираем рабочие приёмы и примеры. Интересны результаты, а не только настройки.', 'Обсуждаем конкретные процессы: от первого черновика до готового результата.', 'Добавляйте задачу, промпт и результат, чтобы другие могли повторить.', 'Можно показать даже маленький эксперимент. Вместе легче сделать следующий шаг.'];
const replies = ['Для меня главное — проверяемый результат. Добавила примеры в ответ.', 'Выложил прототип и описание. Буду рад обратной связи!', 'Сначала фиксирую референс, потом меняю только окружение.', 'Помогает с черновиками, но финальную проверку делаю сам.', 'Приложил короткий шаблон с объяснением каждого шага.', 'Собрала первый небольшой проект — спасибо за советы!'];
const feed: PublicationCardData[] = titles.map((title, i) => ({ id: `demo-topic-${i}`, slug: `demo-topic-${i}`, format: 'TOPIC', type: 'DISCUSSION', title, excerpt: excerpts[i], createdAt: '2026-09-09T09:00:00Z', author: { username: `demo-person-${i}`, displayName: names[i] }, community: communities[i], commentCount: [48,27,18,31,42,16][i], reactionCount: 20+i, viewCount: [842,1200,654,980,1400,421][i], tags: [{ id: `demo-tag-${i}`, slug: `demo-tag-${i}`, label: ['опыт','проект','генерация','практика','промпт','покажи-своё'][i], styleEnabled: false, backgroundColor: colors[i], textColor: '#253026', borderColor: colors[i] }], lastComment: { id: `demo-reply-${i}`, excerpt: replies[i], createdAt: '2026-09-09T10:00:00Z', author: { username: `demo-person-${(i+1)%6}`, displayName: names[(i+1)%6] } } }));
const data: HomeInitialData = { communities, feed, announcements: ['Собираем сообщество о нейросетях', 'Конкурс: покажи свой первый AI-проект', 'Предложите новый раздел FORRUM'].map((title,i)=>({...feed[i], id:`demo-news-${i}`, title})), overview: { stats: { communities: 6, topics: 12843, messages: 327691, usersOnline: 755, recordOnline: 755 }, weekly: { likes: [], activity: names.slice(0,5).map((displayName,i)=>({username:`demo-person-${i}`,displayName,score:100-i*10,reactionCount:80-i*5,topicCount:8-i,commentCount:32-i*4})) }, discussed: feed.map(item=>({...item,viewCount:item.viewCount ?? 0})), banners: [0,1].map(slot=>({slot:slot+1, enabled:true,kind:'promotion' as const,title:slot?'AI для изображений и видео':'Мастерская AI-проектов',imageLight:slot?'/images/home/community-dark.webp':'/images/home/ai-community-dark.webp',imageDark:slot?'/images/home/community-dark.webp':'/images/home/ai-community-dark.webp',href:'/communities',startsAt:'',endsAt:'',disclosure:''})) } };
export default function PreviewHome() { return <HomeDashboard initialData={data} demo/>; }
