'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Heading, Help, ErrorBox } from '@/components/admin/ui';
type Connections = { mail: { hostConfigured: boolean; port: string; senderConfigured: boolean; testInbox: boolean; webUrlConfigured: boolean }; telegram: { tokenConfigured: boolean; pollingEnabled: boolean } };
export default function SettingsPage() {
  const [data, setData] = useState<Connections | null>(null), [error, setError] = useState('');
  async function load() { setError(''); try { setData(await api<Connections>('/admin/connections')); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось загрузить'); } }
  useEffect(() => { void load(); }, []);
  return <><Heading title="Почта и Telegram" description="Проверьте, заданы ли настройки подключения на сервере."><button className="adm-secondary" onClick={() => void load()}>Обновить статус</button></Heading><ErrorBox error={error} retry={() => void load()}/>{!data && !error && <p role="status">Загружаем настройки…</p>}{data && <div className="adm-charts"><section className="adm-panel"><div className="adm-card-title"><h2>Письма форума</h2><Help label="Письма форума">Письма используются для подтверждения регистрации и восстановления пароля. Наличие настроек не доказывает, что сервер доставляет письма.</Help></div><span className="adm-badge">{data.mail.testInbox ? 'Тестовый ящик Mailpit' : 'SMTP-сервер'}</span><dl className="adm-settings-list"><div><dt>Сервер отправки</dt><dd>{data.mail.hostConfigured ? 'Задан' : 'Не задан'}</dd></div><div><dt>Порт</dt><dd>{data.mail.port}</dd></div><div><dt>Отправитель</dt><dd>{data.mail.senderConfigured ? 'Задан' : 'Не задан'}</dd></div><div><dt>Адрес сайта в письмах</dt><dd>{data.mail.webUrlConfigured ? 'Указан с протоколом' : 'Проверьте WEB_URL'}</dd></div></dl><p>{data.mail.testInbox ? 'Письма собираются в Mailpit. По умолчанию они не поступают в личную почту пользователей.' : 'Для проверки доставки запросите письмо для существующего аккаунта и проверьте почтовый ящик.'}</p></section><section className="adm-panel"><div className="adm-card-title"><h2>Telegram</h2><Help label="Telegram">Токен даёт серверу доступ к боту. Здесь показано только наличие настройки, сам токен не передаётся в браузер.</Help></div><dl className="adm-settings-list"><div><dt>Токен бота</dt><dd>{data.telegram.tokenConfigured ? 'Задан' : 'Не задан'}</dd></div><div><dt>Опрос сообщений</dt><dd>{data.telegram.pollingEnabled ? 'Включён' : 'Выключен'}</dd></div></dl><p>Этот экран проверяет конфигурацию. Доступность бота и его права в канале проверяются отдельно.</p></section></div>}<section className="adm-panel"><h2>Где изменить подключение?</h2><p>Пока эти настройки хранятся в Railway: сервис <strong>api → Variables</strong>. Измените нужное значение и примените развёртывание. Эта страница показывает состояние без раскрытия паролей и токенов.</p><details><summary>Какие параметры за что отвечают?</summary><dl className="adm-settings-list"><div><dt>SMTP_HOST / SMTP_PORT</dt><dd>Адрес и порт почтового сервера.</dd></div><div><dt>SMTP_FROM</dt><dd>Имя и адрес отправителя письма.</dd></div><div><dt>WEB_URL</dt><dd>Полный адрес форума: https://4rrum.ru. Используется в ссылках подтверждения.</dd></div><div><dt>TELEGRAM_BOT_TOKEN</dt><dd>Секретный ключ вашего бота.</dd></div></dl></details></section></>;
}
