'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import {Editor} from './editor';
import { Heading, Help, ErrorBox, Empty } from './ui';
type Row = { id: string; username?: string; displayName?: string; email?: string; role?: string; state?: string; emailVerifiedAt?: string | null; createdAt: string; slug?: string; title?: string | null; status?: string; author?: { username: string }; community?: { name: string } };
type Data = { items: Row[]; total: number; page: number; pageSize: number };
const roles: Record<string, string> = { OWNER: 'Владелец', ADMIN: 'Администратор', USER: 'Участник', MEMBER: 'Участник', MODERATOR: 'Модератор' };
const statuses: Record<string, string> = { PUBLISHED: 'Опубликовано', HIDDEN: 'Скрыто', DRAFT: 'Черновик', DELETED: 'Удалено' };
export default function Directory({ kind }: { kind: 'users' | 'publications' }) {
  const users = kind === 'users';
  const [restore,setRestore]=useState(false),[filters,setFilters]=useState({status:'',author:'',category:'',from:'',to:''}),[categories,setCategories]=useState<{slug:string;name:string}[]>([]),[ready,setReady]=useState(false);
  useEffect(()=>{const p=new URLSearchParams(location.search);setFilters({status:p.get('status')??'',author:p.get('author')??'',category:p.get('category')??'',from:p.get('from')??'',to:p.get('to')??''});setSearch(p.get('q')??'');setQuery(p.get('q')??'');setPage(Math.max(1,Number(p.get('page'))||1));setReady(true);if(!users)api<{slug:string;name:string}[]>('/admin/categories').then(setCategories).catch(()=>{});},[users]);
  const [query, setQuery] = useState(''), [search, setSearch] = useState(''), [page, setPage] = useState(1), [revision, setRevision] = useState(0);
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState('');
  const [hiding, setHiding] = useState<string | null>(null), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { if(!ready)return;let active = true;const params=new URLSearchParams({...filters,q:search,page:String(page)});history.replaceState(null,'','?'+params.toString());setError(''); setData(null); api<Data>(`/admin/${kind}?${params}`).then(v => { if (active) setData(v); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [kind, search, page, revision, filters, ready]);
  useEffect(() => { if (hiding) { const element = document.querySelector<HTMLElement>('.adm-confirm'); element?.scrollIntoView({ block: 'nearest' }); element?.querySelector<HTMLElement>('input, textarea')?.focus(); } }, [hiding]);
  async function hide() { if (!hiding || busy) return; setBusy(true); setError(''); try { await api(restore?`/admin/workspace/publications/${hiding}/restore`:`/admin/publications/${hiding}/hide`, { method: 'POST', body: JSON.stringify({ reason }) }); setHiding(null); setReason(''); setMessage(restore?'Публикация восстановлена. Решение записано в журнал.':'Публикация скрыта. Причина записана в журнал.'); setRevision(v => v + 1); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось скрыть'); } finally { setBusy(false); } }
  return <><Heading title={users ? 'Пользователи' : 'Публикации'} description={users ? 'Найдите аккаунт и проверьте его роль и подтверждение почты.' : 'Все материалы форума с поиском и переходом к публикации.'}>{users && <Link className="adm-secondary" href="/admin/roles">Назначить роль в категории</Link>}</Heading>
    <form className="adm-toolbar" onSubmit={e => { e.preventDefault(); setPage(1); setSearch(query.trim()); }}><label className="adm-search"><span className="sr-only">{users ? 'Поиск по имени или почте' : 'Поиск по заголовку'}</span><input maxLength={100} value={query} placeholder={users ? 'Имя, @username или почта' : 'Название публикации'} onChange={e => setQuery(e.target.value.replace(users ? /^@/ : /$^/, ''))}/></label><button className="adm-primary">Найти</button>{search && <button className="adm-secondary" type="button" onClick={() => { setQuery(''); setSearch(''); setPage(1); }}>Сбросить</button>}</form>
    {!users&&<div className="adm-filters"><label>Статус<select value={filters.status} onChange={e=>{setPage(1);setFilters({...filters,status:e.target.value});}}><option value="">Все</option><option value="PUBLISHED">Опубликованы</option><option value="HIDDEN">Скрыты</option><option value="DELETED">Удалены</option></select></label><label>Автор<input value={filters.author} onChange={e=>{setPage(1);setFilters({...filters,author:e.target.value});}} placeholder="username"/></label><label>Категория<select value={filters.category} onChange={e=>{setPage(1);setFilters({...filters,category:e.target.value});}}><option value="">Все категории</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><label>С<input type="date" value={filters.from} onChange={e=>{setPage(1);setFilters({...filters,from:e.target.value});}}/></label><label>По<input type="date" value={filters.to} onChange={e=>{setPage(1);setFilters({...filters,to:e.target.value});}}/></label></div>}
    <ErrorBox error={error} retry={() => setRevision(v => v + 1)}/>{message && <p className="adm-success" role="status">{message}</p>}{!data && !error && <Empty>Загружаем список…</Empty>}
    {data && <section className="adm-panel"><div className="adm-card-title"><h2>Найдено: {data.total}</h2><Help label={users ? 'Подтверждение почты' : 'Скрытие публикации'}>{users ? 'Подтверждённая почта позволяет участвовать в форуме. Смена пароля выполняется владельцем аккаунта через восстановление. Роли в категориях настраиваются отдельно.' : 'Скрытие убирает материал из публичной ленты и сохраняет его в базе. Укажите причину перед подтверждением.'}</Help></div>{!data.items.length ? <Empty>Ничего не найдено. Измените поисковый запрос.</Empty> : <div className="adm-table-wrap"><table><thead><tr><th>{users ? 'Пользователь' : 'Публикация'}</th><th>{users ? 'Почта' : 'Категория'}</th><th>{users ? 'Роль' : 'Статус'}</th><th>{users ? 'Подтверждение' : 'Действие'}</th></tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td><Link href={users ? `/admin/users/${row.username}` : `/p/${row.slug}`}><strong>{users ? row.displayName : row.title || 'Без заголовка'}</strong></Link><small>@{users ? row.username : row.author?.username} · {new Date(row.createdAt).toLocaleDateString('ru-RU')}</small></td><td>{users ? row.email : row.community?.name}</td><td>{users ? roles[row.role ?? ''] || row.role : statuses[row.status ?? ''] || row.status}</td><td>{users ? <span className="adm-badge">{row.state === 'SUSPENDED' ? 'Заблокирован' : row.emailVerifiedAt ? 'Подтверждена' : 'Ожидает подтверждения'}</span> : row.status === 'PUBLISHED' ? <button className="adm-secondary" onClick={() => { setRestore(false);setHiding(row.slug!); setReason(''); }}>Скрыть…</button> : row.status==='HIDDEN'?<button className="adm-secondary" onClick={()=>{setRestore(true);setHiding(row.slug!);setReason('');}}>Восстановить…</button>:'—'}</td></tr>)}</tbody></table></div>}<div className="adm-pagination"><button disabled={page <= 1} onClick={() => setPage(v => v - 1)}>← Назад</button><span>Страница {page} из {Math.max(1, Math.ceil(data.total / data.pageSize))}</span><button disabled={page * data.pageSize >= data.total} onClick={() => setPage(v => v + 1)}>Далее →</button></div></section>}
    {hiding && <Editor title={restore?"Восстановить публикацию?":"Скрыть публикацию?"} dirty={!!reason} busy={busy} onClose={()=>setHiding(null)}><ErrorBox error={error}/><p>{restore?"Материал снова станет доступен участникам форума.":"Материал исчезнет из публичной ленты. Запись останется в базе."}</p><form onSubmit={e => { e.preventDefault(); void hide(); }}><label>Объяснение решения<textarea required minLength={5} maxLength={500} value={reason} onChange={e => setReason(e.target.value)}/></label><div className="adm-toolbar"><button disabled={busy} className="adm-primary">{busy ? 'Сохраняем…' : restore?'Восстановить':'Подтвердить скрытие'}</button><button type="button" disabled={busy} onClick={() => setHiding(null)}>Отмена</button></div></form></Editor>}
  </>;
}
