'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Heading, Help, ErrorBox, Empty } from './ui';
type Row = { id: string; username?: string; displayName?: string; email?: string; role?: string; state?: string; emailVerifiedAt?: string | null; createdAt: string; slug?: string; title?: string | null; status?: string; author?: { username: string }; community?: { name: string } };
type Data = { items: Row[]; total: number; page: number; pageSize: number };
const roles: Record<string, string> = { OWNER: 'Владелец', ADMIN: 'Администратор', USER: 'Участник', MEMBER: 'Участник', MODERATOR: 'Модератор' };
const statuses: Record<string, string> = { PUBLISHED: 'Опубликовано', HIDDEN: 'Скрыто', DRAFT: 'Черновик', DELETED: 'Удалено' };
export default function Directory({ kind }: { kind: 'users' | 'publications' }) {
  const users = kind === 'users';
  const [query, setQuery] = useState(''), [search, setSearch] = useState(''), [page, setPage] = useState(1), [revision, setRevision] = useState(0);
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState('');
  const [hiding, setHiding] = useState<string | null>(null), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { let active = true; setError(''); setData(null); api<Data>(`/admin/${kind}?q=${encodeURIComponent(search)}&page=${page}`).then(v => { if (active) setData(v); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [kind, search, page, revision]);
  useEffect(() => { if (hiding) { const element = document.querySelector<HTMLElement>('.adm-confirm'); element?.scrollIntoView({ block: 'nearest' }); element?.querySelector<HTMLElement>('input, textarea')?.focus(); } }, [hiding]);
  async function hide() { if (!hiding || busy) return; setBusy(true); setError(''); try { await api(`/admin/publications/${hiding}/hide`, { method: 'POST', body: JSON.stringify({ reason }) }); setHiding(null); setReason(''); setMessage('Публикация скрыта. Причина записана в журнал.'); setRevision(v => v + 1); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось скрыть'); } finally { setBusy(false); } }
  return <><Heading title={users ? 'Пользователи' : 'Публикации'} description={users ? 'Найдите аккаунт и проверьте его роль и подтверждение почты.' : 'Все материалы форума с поиском и переходом к публикации.'}>{users && <Link className="adm-secondary" href="/admin/roles">Назначить роль в категории</Link>}</Heading>
    <form className="adm-toolbar" onSubmit={e => { e.preventDefault(); setPage(1); setSearch(query.trim()); }}><label className="adm-search"><span className="sr-only">{users ? 'Поиск по имени или почте' : 'Поиск по заголовку'}</span><input maxLength={100} value={query} placeholder={users ? 'Имя, @username или почта' : 'Название публикации'} onChange={e => setQuery(e.target.value.replace(users ? /^@/ : /$^/, ''))}/></label><button className="adm-primary">Найти</button>{search && <button className="adm-secondary" type="button" onClick={() => { setQuery(''); setSearch(''); setPage(1); }}>Сбросить</button>}</form>
    <ErrorBox error={error} retry={() => setRevision(v => v + 1)}/>{message && <p className="adm-success" role="status">{message}</p>}{!data && !error && <Empty>Загружаем список…</Empty>}
    {data && <section className="adm-panel"><div className="adm-card-title"><h2>Найдено: {data.total}</h2><Help label={users ? 'Подтверждение почты' : 'Скрытие публикации'}>{users ? 'Подтверждённая почта позволяет участвовать в форуме. Смена пароля выполняется владельцем аккаунта через восстановление. Роли в категориях настраиваются отдельно.' : 'Скрытие убирает материал из публичной ленты и сохраняет его в базе. Укажите причину перед подтверждением.'}</Help></div>{!data.items.length ? <Empty>Ничего не найдено. Измените поисковый запрос.</Empty> : <div className="adm-table-wrap"><table><thead><tr><th>{users ? 'Пользователь' : 'Публикация'}</th><th>{users ? 'Почта' : 'Категория'}</th><th>{users ? 'Роль' : 'Статус'}</th><th>{users ? 'Подтверждение' : 'Действие'}</th></tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td><Link href={users ? `/u/${row.username}` : `/p/${row.slug}`}><strong>{users ? row.displayName : row.title || 'Без заголовка'}</strong></Link><small>@{users ? row.username : row.author?.username} · {new Date(row.createdAt).toLocaleDateString('ru-RU')}</small></td><td>{users ? row.email : row.community?.name}</td><td>{users ? roles[row.role ?? ''] || row.role : statuses[row.status ?? ''] || row.status}</td><td>{users ? <span className="adm-badge">{row.state === 'SUSPENDED' ? 'Заблокирован' : row.emailVerifiedAt ? 'Подтверждена' : 'Ожидает подтверждения'}</span> : row.status === 'PUBLISHED' ? <button className="adm-secondary" onClick={() => { setHiding(row.slug!); setReason(''); }}>Скрыть…</button> : '—'}</td></tr>)}</tbody></table></div>}<div className="adm-pagination"><button disabled={page <= 1} onClick={() => setPage(v => v - 1)}>← Назад</button><span>Страница {page} из {Math.max(1, Math.ceil(data.total / data.pageSize))}</span><button disabled={page * data.pageSize >= data.total} onClick={() => setPage(v => v + 1)}>Далее →</button></div></section>}
    {hiding && <section className="adm-panel adm-confirm"><h2>Скрыть публикацию?</h2><p>Материал исчезнет из публичной ленты. Запись останется в базе.</p><form onSubmit={e => { e.preventDefault(); void hide(); }}><label>Причина скрытия<textarea required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)}/></label><div className="adm-toolbar"><button disabled={busy} className="adm-primary">{busy ? 'Сохраняем…' : 'Подтвердить скрытие'}</button><button type="button" disabled={busy} onClick={() => setHiding(null)}>Отмена</button></div></form></section>}
  </>;
}
