'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Heading, Help, ErrorBox, Empty } from '@/components/admin/ui';
type Category = { id: string; parentId: string | null; name: string; slug: string; description: string; shortDescription: string | null; status: string; _count: { publications: number; subscriptions: number } };
export default function CategoriesPage() {
  const [items, setItems] = useState<Category[] | null>(null), [error, setError] = useState(''), [query, setQuery] = useState('');
  const [edit, setEdit] = useState<Category | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  async function load() { setError(''); try { setItems(await api<Category[]>('/admin/categories')); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось загрузить'); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (edit?.id) { const element = document.querySelector<HTMLElement>('.adm-editor'); element?.scrollIntoView({ block: 'nearest' }); element?.querySelector<HTMLElement>('input, textarea')?.focus(); } }, [edit?.id]);
  async function save() { if (!edit || busy) return; setBusy(true); setError(''); try { await api(`/admin/categories/${edit.id}`, { method: 'PUT', body: JSON.stringify({ name: edit.name, description: edit.description, shortDescription: edit.shortDescription ?? '' }) }); setEdit(null); setMessage('Категория сохранена. Адрес и публикации остались прежними.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось сохранить'); } finally { setBusy(false); } }
  const ordered: (Category & { depth: number })[] = [];
  const visited = new Set<string>();
  const walk = (parent: string | null, depth: number) => { for (const item of items ?? []) { if (item.parentId !== parent || visited.has(item.id)) continue; visited.add(item.id); ordered.push({ ...item, depth }); walk(item.id, depth + 1); } };
  walk(null, 0); for (const item of items ?? []) if (!visited.has(item.id)) ordered.push({ ...item, depth: 0 });
  return <><Heading title="Категории" description="Все разделы форума в одном дереве. Откройте категорию, чтобы изменить название и описание."><Link className="adm-primary" href="/admin/categories/new">+ Создать категорию</Link></Heading>
    <section className="adm-panel adm-taxonomy-callout"><div><strong>Перестроить форум под AI</strong><p>Готовая структура с разделом «Видеоигры». Сначала покажем все переносы.</p></div><Link className="adm-secondary" href="/admin/ai-taxonomy">Посмотреть изменения →</Link><Help label="Перестройка категорий">Это отдельное действие с подтверждением. Открытие предварительного просмотра ничего не меняет. Существующие темы и адреса сохраняются.</Help></section>
    <label className="adm-search"><span className="sr-only">Поиск категории</span><input placeholder="Найти категорию…" value={query} onChange={e => setQuery(e.target.value)}/></label><ErrorBox error={error} retry={() => void load()}/>{message && <p className="adm-success" role="status">{message}</p>}
    {items === null && !error && <Empty>Загружаем дерево…</Empty>}{items && <div className="adm-panel adm-category-list">{ordered.filter(row => row.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(row => <article key={row.id}><div style={{ paddingLeft: Math.min(row.depth, 5) * 16 }}><span className="adm-category-icon" aria-hidden="true">{row.depth ? '↳' : '▦'}</span><div><strong>{row.name}</strong><small>{row.shortDescription || row.slug}{row.status !== 'ACTIVE' ? ' · неактивна' : ''}</small></div></div><span className="adm-muted">{row._count.publications} публикаций · {row._count.subscriptions} подписчиков</span><button className="adm-secondary" onClick={() => { setEdit({ ...row }); setMessage(''); }}>Изменить</button></article>)}{!ordered.some(row => row.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())) && <Empty>Категории не найдены.</Empty>}</div>}
    {edit && <section className="adm-panel adm-editor"><h2>Изменить «{items?.find(row => row.id === edit.id)?.name}»</h2><form onSubmit={e => { e.preventDefault(); void save(); }}><fieldset disabled={busy}><label>Название <input required minLength={2} maxLength={60} value={edit.name} onChange={e => setEdit({ ...edit, name: e.target.value })}/></label><label>Короткое описание <input maxLength={180} value={edit.shortDescription ?? ''} onChange={e => setEdit({ ...edit, shortDescription: e.target.value })}/></label><label>Полное описание <textarea required minLength={20} maxLength={2000} value={edit.description} onChange={e => setEdit({ ...edit, description: e.target.value })}/></label><p className="adm-muted">Адрес: /communities/{edit.slug}. Переименование не меняет ссылки.</p><div className="adm-toolbar"><button className="adm-primary">{busy ? 'Сохраняем…' : 'Сохранить категорию'}</button><button type="button" className="adm-secondary" onClick={() => setEdit(null)}>Отмена</button></div></fieldset></form></section>}
  </>;
}
