export const EXPEDITION_ENERGY_REGEN_SECONDS = 30 * 60;

export const EXPEDITION_DEPTHS = [
  { id: 1, name: 'Вход в окраины', energyCost: 1, durationSeconds: 20, minPower: 1, xp: 25, metal: [6, 12], cloth: [2, 5], scrap: [1, 4], oldParts: [0, 1] },
  { id: 2, name: 'Ломовые дворы', energyCost: 2, durationSeconds: 45, minPower: 4, xp: 35, metal: [10, 18], cloth: [3, 7], scrap: [3, 7], oldParts: [0, 2] },
  { id: 3, name: 'Старые кварталы', energyCost: 2, durationSeconds: 90, minPower: 7, xp: 45, metal: [12, 22], cloth: [4, 8], scrap: [5, 10], oldParts: [1, 3] },
  { id: 4, name: 'Промышленный двор', energyCost: 3, durationSeconds: 180, minPower: 10, xp: 60, metal: [16, 28], cloth: [4, 10], scrap: [7, 13], oldParts: [2, 5] },
  { id: 5, name: 'Реакторная зона', energyCost: 4, durationSeconds: 300, minPower: 14, xp: 80, metal: [20, 36], cloth: [5, 12], scrap: [9, 17], oldParts: [3, 7] },
] as const;

export const EXPEDITION_ITEM_SEEDS = [
  {
    id: 'exp-hood-gatherer',
    slug: 'exp-hood-gatherer',
    name: 'Капюшон Собирателя',
    description: 'Потрёпанный капюшон исследователя окраин.',
    type: 'GAME_HEAD',
    rarity: 'COMMON',
    previewKey: 'hood',
    maxSupply: 5000,
    minimumDepth: 1,
    weight: 100,
    power: 2,
  },
  {
    id: 'exp-boots-iron-step',
    slug: 'exp-boots-iron-step',
    name: 'Сапоги Железного Шага',
    description: 'Старая кожа усилена найденными металлическими пластинами.',
    type: 'GAME_FEET',
    rarity: 'UNCOMMON',
    previewKey: 'boots',
    maxSupply: 3000,
    minimumDepth: 1,
    weight: 72,
    power: 4,
  },
  {
    id: 'exp-gloves-servomaster',
    slug: 'exp-gloves-servomaster',
    name: 'Перчатки Сервомастера',
    description: 'В одной из перчаток сохранился рабочий усилитель хвата.',
    type: 'GAME_GLOVES',
    rarity: 'UNCOMMON',
    previewKey: 'gloves',
    maxSupply: 4000,
    minimumDepth: 2,
    weight: 65,
    power: 4,
  },
  {
    id: 'exp-chest-old-guard',
    slug: 'exp-chest-old-guard',
    name: 'Панцирь Старой Стражи',
    description: 'Кузнечная броня поверх уцелевших пластин прошлого.',
    type: 'GAME_CHEST',
    rarity: 'UNCOMMON',
    previewKey: 'chest',
    maxSupply: 2500,
    minimumDepth: 2,
    weight: 55,
    power: 5,
  },
  {
    id: 'exp-shoulders-frontier',
    slug: 'exp-shoulders-frontier',
    name: 'Наплечники Рубежа',
    description: 'Тяжёлые наплечники дозорных старых кварталов.',
    type: 'GAME_SHOULDERS',
    rarity: 'RARE',
    previewKey: 'shoulders',
    maxSupply: 650,
    minimumDepth: 3,
    weight: 26,
    power: 7,
  },
  {
    id: 'exp-cloak-blue-banner',
    slug: 'exp-cloak-blue-banner',
    name: 'Плащ Синего Знамени',
    description: 'Редкий плащ исчезнувшего дозорного дома.',
    type: 'GAME_CLOAK',
    rarity: 'RARE',
    previewKey: 'cloak',
    maxSupply: 500,
    minimumDepth: 3,
    weight: 20,
    power: 8,
  },
  {
    id: 'exp-blade-last-circuit',
    slug: 'exp-blade-last-circuit',
    name: 'Клинок Последнего Контура',
    description: 'Клинок, в котором до сих пор пробегает холодный ток.',
    type: 'GAME_MAIN_HAND',
    rarity: 'RARE',
    previewKey: 'sword',
    maxSupply: 400,
    minimumDepth: 4,
    weight: 14,
    power: 11,
  },
  {
    id: 'exp-heart-beacon',
    slug: 'exp-heart-beacon',
    name: 'Сердце Маяка',
    description: 'Живой свет древнего навигационного узла.',
    type: 'GAME_RELIC_1',
    rarity: 'EPIC',
    previewKey: 'relic',
    maxSupply: 60,
    minimumDepth: 5,
    weight: 3,
    power: 14,
  },
] as const;
