import 'reflect-metadata';
import test from 'node:test';import assert from 'node:assert/strict';import {ConfigService} from '@nestjs/config';
import {WorkspaceService,pageParams} from '../src/admin/workspace.service.js';import {customWindow} from '../src/admin/analytics.js';import type {PrismaService} from '../src/prisma/prisma.service.js';
const dto={name:'Категория',description:'Описание категории достаточно длинное',shortDescription:'',parentId:null,sortOrder:2,status:'ACTIVE' as const};
function fixture(nodes:{id:string;parentId:string|null;status:string}[]){const changes:unknown[]=[];const tx={$executeRaw:async()=>0,community:{findUnique:async()=>nodes[0],findMany:async()=>nodes,update:async(v:unknown)=>{changes.push(v);}},auditLog:{create:async(v:unknown)=>changes.push(v)}};const db={$transaction:async(fn:(v:typeof tx)=>unknown)=>fn(tx)};return {service:new WorkspaceService(db as unknown as PrismaService,new ConfigService()),changes};}
test('category move rejects self and descendant cycles before writing',async()=>{const f=fixture([{id:'a',parentId:null,status:'ACTIVE'},{id:'b',parentId:'a',status:'ACTIVE'}]);await assert.rejects(f.service.category('a',{...dto,parentId:'b'},'owner'));assert.equal(f.changes.length,0);});
test('category archive refuses active children',async()=>{const f=fixture([{id:'a',parentId:null,status:'ACTIVE'},{id:'b',parentId:'a',status:'ACTIVE'}]);await assert.rejects(f.service.category('a',{...dto,status:'ARCHIVED'},'owner'));assert.equal(f.changes.length,0);});
test('category move refuses archived parent',async()=>{const f=fixture([{id:'a',parentId:null,status:'ACTIVE'},{id:'b',parentId:null,status:'ARCHIVED'}]);await assert.rejects(f.service.category('a',{...dto,parentId:'b'},'owner'));});
test('category update preserves slug and content and records an audit entry',async()=>{const f=fixture([{id:'a',parentId:null,status:'ACTIVE'}]);await f.service.category('a',dto,'owner');assert.equal(f.changes.length,2);const update=f.changes[0] as {data:Record<string,unknown>};assert.equal(update.data.sortOrder,2);assert.ok(!('slug' in update.data));assert.ok(!('publications' in update.data));});
test('custom analytics dates are UTC, bounded and exclude today',()=>{const now=new Date('2026-09-12T08:00:00Z');const w=customWindow('2026-09-01','2026-09-11',now);assert.equal(w.days,11);assert.equal(w.end.toISOString(),'2026-09-12T00:00:00.000Z');assert.throws(()=>customWindow('2026-09-12','2026-09-12',now));assert.throws(()=>customWindow('2026-02-30','2026-03-01',now));assert.throws(()=>customWindow('2020-01-01','2026-09-01',now));});
test('pagination rejects oversized and invalid search input',()=>{for(const p of ['0','-1','1.5','100001'])assert.throws(()=>pageParams(p));assert.throws(()=>pageParams('1','x'.repeat(101)));});
test('diagnostic config failure does not expose credentials or throw',async()=>{const s=new WorkspaceService({} as PrismaService,new ConfigService({NODE_ENV:'production',SMTP_HOST:'',SMTP_PASS:'secret'}));const result=await s.diagnose();assert.equal(result.mail.ok,false);assert.ok(!JSON.stringify(result).includes('secret'));});
test('restoration refuses deleted content',async()=>{let writes=0;const db={$transaction:async(fn:(tx:unknown)=>unknown)=>fn({publication:{findUnique:async()=>({id:'p',status:'DELETED'}),update:async()=>{writes++;}}})};const s=new WorkspaceService(db as unknown as PrismaService,new ConfigService());await assert.rejects(s.restore('p','Ошибка скрытия','owner'));assert.equal(writes,0);});
